import { Alert } from 'react-native';
import { RiskAlert, ThreatCategory } from './riskEngine';

/**
 * Platform reporting — flags harmful content to the app/platform where it occurred.
 *
 * How it works:
 * 1. Custodian detects a threat (grooming, bullying, etc.)
 * 2. Parent reviews the alert in the dashboard
 * 3. Parent taps "Report to Platform" → generates a report
 * 4. Opens the platform's reporting flow or sends via their API
 *
 * Supported platforms and their reporting mechanisms:
 * - Roblox: roblox.com/report-abuse (deep link or in-app)
 * - Discord: dis.gd/report (web form)
 * - Minecraft: minecraft.net/en-us/report (web form)
 * - Fortnite: epicgames.com/help (web form)
 * - TikTok: in-app report + support.tiktok.com
 * - Snapchat: support.snapchat.com/report
 * - Instagram: help.instagram.com/report
 *
 * In production: direct API integration with platform trust & safety teams.
 * MVP: generates structured report + opens platform reporting URL.
 */

interface PlatformInfo {
  name: string;
  reportUrl: string;
  supportsDirectApi: boolean;
}

const PLATFORMS: Record<string, PlatformInfo> = {
  roblox: { name: 'Roblox', reportUrl: 'https://www.roblox.com/report-abuse', supportsDirectApi: false },
  discord: { name: 'Discord', reportUrl: 'https://dis.gd/report', supportsDirectApi: false },
  minecraft: { name: 'Minecraft', reportUrl: 'https://minecraft.net/en-us/report', supportsDirectApi: false },
  fortnite: { name: 'Fortnite', reportUrl: 'https://www.epicgames.com/help', supportsDirectApi: false },
  tiktok: { name: 'TikTok', reportUrl: 'https://support.tiktok.com/report', supportsDirectApi: false },
  snapchat: { name: 'Snapchat', reportUrl: 'https://support.snapchat.com/report', supportsDirectApi: false },
  instagram: { name: 'Instagram', reportUrl: 'https://help.instagram.com/report', supportsDirectApi: false },
  messenger: { name: 'Messenger', reportUrl: 'https://www.facebook.com/help/messenger-app/reporting', supportsDirectApi: false },
};

const CATEGORY_LABELS: Record<ThreatCategory, string> = {
  grooming: 'Sexual solicitation / grooming of a minor',
  bullying: 'Harassment / bullying',
  selfHarm: 'Self-harm / suicide content',
  violence: 'Violent threats',
  contentWellness: 'Harmful content directed at minors',
};

export function generateReport(alert: RiskAlert): string {
  const categoryLabel = CATEGORY_LABELS[alert.category] || 'Harmful content';
  const timestamp = new Date(alert.timestamp).toLocaleString();

  return [
    `REPORT: ${categoryLabel}`,
    `Date/Time: ${timestamp}`,
    `Source: ${alert.sourceApp}`,
    `Risk Score: ${alert.score}/100`,
    ``,
    `Flagged content:`,
    `"${alert.snippet}"`,
    ``,
    `This report was generated by Custodian, an on-device child safety tool.`,
    `The content was flagged by automated pattern analysis and reviewed by a parent/guardian.`,
    `Please investigate this user's activity on your platform.`,
  ].join('\n');
}

export function getReportUrl(sourceApp: string): string | null {
  const key = sourceApp.toLowerCase().replace(/\s/g, '');
  const platform = PLATFORMS[key];
  return platform?.reportUrl || null;
}

export function getPlatformName(sourceApp: string): string {
  const key = sourceApp.toLowerCase().replace(/\s/g, '');
  return PLATFORMS[key]?.name || sourceApp;
}

export function promptReport(alert: RiskAlert, onOpenUrl: (url: string) => void) {
  const report = generateReport(alert);
  const reportUrl = getReportUrl(alert.sourceApp);
  const platformName = getPlatformName(alert.sourceApp);

  const buttons: any[] = [
    { text: 'Cancel', style: 'cancel' },
    {
      text: 'Copy Report',
      onPress: () => {
        // In production, use Clipboard API
        Alert.alert('Report Copied', 'Paste it into the platform\'s reporting form.');
      },
    },
  ];

  if (reportUrl) {
    buttons.push({
      text: `Open ${platformName} Report`,
      onPress: () => onOpenUrl(reportUrl),
    });
  }

  Alert.alert(
    `Report to ${platformName}`,
    `This will generate a report about the flagged content. You can submit it to ${platformName}'s trust & safety team.\n\n${report.substring(0, 200)}...`,
    buttons
  );
}
